alias: Baby Keypad Controls (combined)
description: Handles sleep timer, diaper logs, and station light from 2x4 keypad
mode: single

trigger:
  # B1: Wet diaper
  - platform: event
    event_type: esphome.keypad_2x4_b1
    event_
      title: single_click
    id: diaper_wet
  # B2: Solid diaper
  - platform: event
    event_type: esphome.keypad_2x4_b2
    event_
      title: single_click
    id: diaper_solid
  # B3: Start Sleep Timer
  - platform: event
    event_type: esphome.keypad_2x4_b3
    event_
      title: single_click
    id: sleep_start
  # B4: Add Sleep from timer
  - platform: event
    event_type: esphome.keypad_2x4_b4
    event_
      title: single_click
    id: sleep_add_from_timer
  # B5: Wet and Solid
  - platform: event
    event_type: esphome.keypad_2x4_b5
    event_
      title: single_click
    id: diaper_wet_solid
  # B8: Toggle changing-station light
  - platform: event
    event_type: esphome.keypad_2x4_b8
    event_
      title: single_click
    id: change_station_light

condition: []

action:
  - choose:
      # Start Sleep Timer
      - conditions:
          - condition: trigger
            id: sleep_start
        sequence:
          - service: babybuddy.start_timer
            
              name: Sleep Timer
            target:
              entity_id: switch.{baby-name}_timer
          - device_id: bf4bee2885341428dfc1eb0900dd52e2
            domain: light
            entity_id: light.keypad_white_led
            type: flash

      # Add Sleep from existing timer
      - conditions:
          - condition: trigger
            id: sleep_add_from_timer
        sequence:
          - service: babybuddy.add_sleep
            
              timer: true
            target:
              entity_id: switch.{baby-name}_timer
          - device_id: bf4bee2885341428dfc1eb0900dd52e2
            domain: light
            entity_id: light.keypad_white_led
            type: flash

      # Diaper: Wet
      - conditions:
          - condition: trigger
            id: diaper_wet
        sequence:
          - service: babybuddy.add_diaper_change
            
              type: Wet
              notes: From Keypad
            target:
              entity_id: sensor.baby_{baby-name}
          - device_id: bf4bee2885341428dfc1eb0900dd52e2
            domain: light
            entity_id: light.keypad_white_led
            type: flash

      # Diaper: Solid
      - conditions:
          - condition: trigger
            id: diaper_solid
        sequence:
          - service: babybuddy.add_diaper_change
            
              type: Solid
              notes: From Keypad
            target:
              entity_id: sensor.baby_{baby-name}
          - device_id: bf4bee2885341428dfc1eb0900dd52e2
            domain: light
            entity_id: light.keypad_white_led
            type: flash

      # Diaper: Wet and Solid
      - conditions:
          - condition: trigger
            id: diaper_wet_solid
        sequence:
          - service: babybuddy.add_diaper_change
            
              type: Wet and Solid
              notes: From Keypad
            target:
              entity_id: sensor.baby_{baby-name}
          - device_id: bf4bee2885341428dfc1eb0900dd52e2
            domain: light
            entity_id: light.keypad_white_led
            type: flash

      # Change station light toggle
      - conditions:
          - condition: trigger
            id: change_station_light
        sequence:
          - type: toggle
            device_id: 7ef87f6924c797e75020341fe1d2b21c
            entity_id: switch.brown_lamp
            domain: switch
